services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_ENVIRONMENT=Development



